
package com.synergy.bank.payee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SynergyPayeeServiceProvider", targetNamespace = "http://www.bank.synergy.com/payee/", wsdlLocation = "file:/C:/Users/Nani/workspace/synergy-bank/src/main/webapp/xsd/synergy-payee.wsdl")
public class SynergyPayeeServiceProvider
    extends Service
{

    private final static URL SYNERGYPAYEESERVICEPROVIDER_WSDL_LOCATION;
    private final static WebServiceException SYNERGYPAYEESERVICEPROVIDER_EXCEPTION;
    private final static QName SYNERGYPAYEESERVICEPROVIDER_QNAME = new QName("http://www.bank.synergy.com/payee/", "SynergyPayeeServiceProvider");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Nani/workspace/synergy-bank/src/main/webapp/xsd/synergy-payee.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYNERGYPAYEESERVICEPROVIDER_WSDL_LOCATION = url;
        SYNERGYPAYEESERVICEPROVIDER_EXCEPTION = e;
    }

    public SynergyPayeeServiceProvider() {
        super(__getWsdlLocation(), SYNERGYPAYEESERVICEPROVIDER_QNAME);
    }

    public SynergyPayeeServiceProvider(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYNERGYPAYEESERVICEPROVIDER_QNAME, features);
    }

    public SynergyPayeeServiceProvider(URL wsdlLocation) {
        super(wsdlLocation, SYNERGYPAYEESERVICEPROVIDER_QNAME);
    }

    public SynergyPayeeServiceProvider(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYNERGYPAYEESERVICEPROVIDER_QNAME, features);
    }

    public SynergyPayeeServiceProvider(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SynergyPayeeServiceProvider(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SynergyPayeeService
     */
    @WebEndpoint(name = "SynergyPayeeServicePort")
    public SynergyPayeeService getSynergyPayeeServicePort() {
        return super.getPort(new QName("http://www.bank.synergy.com/payee/", "SynergyPayeeServicePort"), SynergyPayeeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SynergyPayeeService
     */
    @WebEndpoint(name = "SynergyPayeeServicePort")
    public SynergyPayeeService getSynergyPayeeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bank.synergy.com/payee/", "SynergyPayeeServicePort"), SynergyPayeeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYNERGYPAYEESERVICEPROVIDER_EXCEPTION!= null) {
            throw SYNERGYPAYEESERVICEPROVIDER_EXCEPTION;
        }
        return SYNERGYPAYEESERVICEPROVIDER_WSDL_LOCATION;
    }

}
