
package com.synergy.bank.registration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
//00

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SynergyRegistrationService", targetNamespace = "http://www.bank.synergy.com/registration/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SynergyRegistrationService {


    /**
     * 
     * @param pregistrationMessageInput
     * @return
     *     returns com.synergy.bank.registration.RegistrationSenderRESVO
     */
    @WebMethod(action = "http://www.bank.synergy.com/customer/customerRegistration")
    @WebResult(name = "registrationres", targetNamespace = "http://www.bank.synergy.com/registration/", partName = "pregistrationMessageResponse")
    public RegistrationSenderRESVO customerRegistration(
        @WebParam(name = "registrationInput", targetNamespace = "http://www.bank.synergy.com/registration/", partName = "pregistrationMessageInput")
        RegistrationSenderVO pregistrationMessageInput);

}
