
package com.synergy.bank.registration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SynergyRegistrationService", targetNamespace = "http://www.bank.synergy.com/registration/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SynergyRegistrationService {


    /**
     * 
     * @param registrationInput
     * @return
     *     returns com.synergy.bank.registration.RegistrationOutputVO
     */
    @WebMethod(action = "http://www.bank.synergy.com/registration/addCustomer")
    @WebResult(name = "registrationVOOutput", targetNamespace = "http://www.bank.synergy.com/registration/", partName = "registrationResponse")
    public RegistrationOutputVO addCustomer(
        @WebParam(name = "registrationVOInput", targetNamespace = "http://www.bank.synergy.com/registration/", partName = "registrationInput")
        RegistrationInputVO registrationInput);

}
