
package com.synergy.bank.email;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SynergyEMailService", targetNamespace = "http://www.bank.synergy.com/email/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SynergyEMailService {


    /**
     * 
     * @param pemailMessageInput
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.bank.synergy.com/email/sendEMail")
    @WebResult(name = "emailResponse", targetNamespace = "http://www.bank.synergy.com/email/", partName = "remailMessageResponse")
    public String sendEmail(
        @WebParam(name = "eMailSenderVOInput", targetNamespace = "http://www.bank.synergy.com/email/", partName = "pemailMessageInput")
        EMailSenderVO pemailMessageInput);

}
